### Hi there 👋 I am Fabrice

* I am currently working on Eclipse Che / Red Hat OpenShift Dev Spaces documentation.
* I am interested in documentation single-sourcing and testing, #DocOps, #TestTheDocs, #WriteTheDocs, and more specifically #AsciiDoc, #Antora, #HTMLtest, and #Vale.
* I am also interested in IT infrastructure automation, #Kubernetes, #Ansible.

<!--
**themr0c/themr0c** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->


![Fabrice Flore-Thébault's GitHub stats](https://github-readme-stats.vercel.app/api?username=themr0c&show_icons=true&theme=transparent)
